services:
  - type: web
    name: marrybrown-inventory
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn marrybrown_inventory.wsgi
    envVars:
      - key: DJANGO_DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "marrybrown-inventory.onrender.com,127.0.0.1,localhost"
